# Generated by Django 4.2 on 2023-05-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todaysignlan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
