# Generated by Django 4.2 on 2023-05-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todaysignlan', '0002_delete_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='signs/')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
